config/routes.rb
Rails.application.routes.draw do
  resources :reports

  root to: 'visitors#index'
  devise_for :users
  resources :users
  get '/oauth2callback' => 'reports#outh_response', as: 'reports_outh_path'
end

app/models/report.rb
class Report < ActiveRecord::Base
	extend Legato::Model

  metrics :pageviews, :uniquePageviews, :sessions, :users, :newUsers, :exits
  dimensions :pagePathLevel1, :sessionCount, :userType, :userDefinedValue, :operating_system, :browser

  filter(:by_index_in_path_level_1) {|page_path_level1| contains(:pagePathLevel1, 'index')}

  # all reuslts query
  def self.query(profile, start_date, end_date)
    Report.results(profile,
                      :start_date => start_date,
                      :end_date => end_date
    )
    # Just for reference, sorting descending by Report is done by:   :sort => '-Report'
  end

  # query index
  def self.query_index(profile, start_date, end_date)
    Report.by_index_in_path_level_1.results(profile,
                                               :start_date => start_date,
                                               :end_date => end_date
    )
  end

  # get pageviews
  def self.get_pageview(profile, start_date, end_date)
    pageviews = []
    Report.query(profile, start_date, end_date).each do |result|
      # Just print the pageviews & unique-pageviews, for example
      pageviews << result.try(:pageviews)
      # puts result.try(:uniquePageviews)
    end
    pageviews = pageviews.map(&:to_i)
    return pageviews.inject(:+)
  end

  # get session count
  def self.get_session_count(profile, start_date, end_date)
    sessions = []
    Report.query(profile, start_date, end_date).each do |result|
      # Just print the session count
      sessions << result.try(:sessionCount)
    end
    sessions = sessions.map(&:to_i)
    return sessions.inject(:+)
  end

  # get session count
  def self.get_user_count(profile, start_date, end_date)
    users = []
    Report.query(profile, start_date, end_date).each do |result|
      # Just print the session count
      users << result.try(:users)
    end
    users = users.map(&:to_i)
    return users.inject(:+)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  LEGATO_OAUTH_CLIENT_ID='941417668948-sm0mnqcrvnojqanmn1ji9969sihkam74.apps.googleusercontent.com'
  LEGATO_OAUTH_SECRET_KEY='RITCXfzU8B-NHaH2pKfYmFKt'

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
    google_access_token
  end

  # GET client auth token
  # GET response json
  def google_access_token
    $client = OAuth2::Client.new(LEGATO_OAUTH_CLIENT_ID, LEGATO_OAUTH_SECRET_KEY, {
      :authorize_url => 'https://accounts.google.com/o/oauth2/auth',
      :token_url => 'https://accounts.google.com/o/oauth2/token'
    })
    @url = $client.auth_code.authorize_url({
      :scope => 'https://www.googleapis.com/auth/analytics.readonly',
      :redirect_uri => 'http://localhost:3000/oauth2callback',
      :access_type => 'offline'
    })
    redirect_to @url
  end

  # GET access auth token
  # GET response json
  def outh_response
    @reports = Report.all
    users = []
    names = []
    begin
      access_token = $client.auth_code.get_token(params[:code], :redirect_uri => 'http://localhost:3000/oauth2callback')
      @response_json = access_token.get('https://www.googleapis.com/analytics/v3/management/accounts').body
      user = Legato::User.new(access_token)
      profile = user.profiles.first
      @users = Report.get_user_count(profile, 9.day.ago, 0.day.ago)
      @sessions = Report.get_session_count(profile, 9.day.ago, 0.day.ago)
      @pageviews = Report.get_pageview(profile, 9.day.ago, 0.day.ago)
      @name = user.profiles.map(&:name).first
      @names = user.profiles.map(&:name)
      render :index
    rescue
      respond_to do |format|
        format.html {render :index, alert: 'Analytics not found.' }
      end
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:page_view, :sessions, :date, :site_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
	<li><%= link_to 'Reports', reports_path %></li>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Boot App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Boot App" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script type="text/javascript" src="http://www.amcharts.com/lib/3/amcharts.js"></script>
    <script type="text/javascript" src="http://www.amcharts.com/lib/3/serial.js"></script>
    <script type="text/javascript" src="http://www.amcharts.com/lib/3/themes/none.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/reports/_analytics.html.erb
<style type="text/css">
	#chartdiv {
	width		: 100%;
	height		: 500px;
	font-size	: 11px;
	}			
</style>

<%= select_tag "Account", options_for_select(@names.collect {|x| [x]}) rescue nil %>
 
<%= label_tag 'start_date', 'Start Date: ' %><%= date_select("Start Date", "start_on") %>&nbsp;
<%= label_tag 'end_date', 'End Date: ' %><%= date_select("End Date", "end_on") %>

<h3>Analytics for the account response JS</h3>
<p>
  <%#= @response_json rescue nil %>
  <%= @name %>
</p>

<h3>Users</h3>
<p>
  <%= @users rescue nil %>
</p>

<h3>Sessions</h3>
<p>
  <%= @sessions rescue nil %>
</p>

<h3>Pageviews</h3>
<p>
  <%= @pageviews rescue nil %>
</p>

<br>

<div id="chartdiv"></div>

<script type="text/javascript">
	var chart = AmCharts.makeChart("chartdiv", {
    "type": "serial",
    "theme": "none",
     "pathToImages":"http://www.amcharts.com/lib/3/images/",
    "dataProvider": [{
        "values": "Users",
        "visits": <%= @users rescue nil %>,
        "color": "#FF0F00"
    }, {
        "values": "Sessions",
        "visits": <%= @sessions rescue nil %>,
        "color": "#FF6600"
    }, {
        "values": "Pageviews",
        "visits": <%= @pageviews rescue nil %>,
        "color": "#FF9E01"
    }],
    "valueAxes": [{
        "axisAlpha": 0,
        "position": "left",
        "title": "Google analytics values"
    }],
    "startDuration": 1,
    "graphs": [{
        "balloonText": "<b>[[category]]: [[value]]</b>",
        "colorField": "color",
        "fillAlphas": 0.9,
        "lineAlpha": 0.2,
        "type": "column",
        "valueField": "visits"
    }],
    "chartCursor": {
        "categoryBalloonEnabled": false,
        "cursorAlpha": 0,
        "zoomable": false
    },
    "categoryField": "values",
    "categoryAxis": {
        "gridPosition": "start",
        "labelRotation": 45
    },
    "amExport":{}
     
});
</script>

app/views/reports/_form.html.erb
<%= simple_form_for(@report) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :page_view %>
    <%= f.input :sessions %>
    <%= f.input :date %>
    <%= f.input :site_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Analytics reports</h1>
<!-- 
<table>
  <thead>
    <tr>
      <th>Page view</th>
      <th>Sessions</th>
      <th>Date</th>
      <th>Site</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%#= report.page_view %></td>
        <td><%#= report.sessions %></td>
        <td><%#= report.date %></td>
        <td><%#= report.site_id %></td>
        <td><%#= link_to 'Show', report %></td>
        <td><%#= link_to 'Edit', edit_report_path(report) %></td>
        <td><%#= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<%= render partial: "analytics" %>

<%#= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Page view:</strong>
  <%= @report.page_view %>
</p>

<p>
  <strong>Sessions:</strong>
  <%= @report.sessions %>
</p>

<p>
  <strong>Date:</strong>
  <%= @report.date %>
</p>

<p>
  <strong>Site:</strong>
  <%= @report.site_id %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>